---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-cloudcms
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    # FIXME: Change the NFS Server
    path: "/var/nfs/storage/cloudcms"
    server: storage.fr.urantiacloud.com
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-cloudcms
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
